name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'       # 只在打 tag 时触发

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x  # 替换为你实际的 .NET 版本

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: ./build.sh Publish